## Leitura do dataset CSV

## Importando bibliotecas
- Utilização de bibliotecas em todas as etapas (Bronze, Prata e Gold)

In [2]:
%pip install seaborn
%pip install pandas
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Requirement already satisfied: seaborn in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from seaborn) (2.5.2)
Requirement already satisfied: pandas>=1.2 in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from seaborn) (3.0.5)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from seaborn) (3.11.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.1)
Requirement already satisfied: packaging>=20.0 in C:\Users\52068085801\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.3)
Requirement already satisfied: pillow>=9 in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\52068085801\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas>=1.2->seaborn) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\52068085801\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: pandas in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\52068085801\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\52068085801\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
df = pd.read_csv("history.csv")

# Conhecendo o Dataset:
- Primeiros e últimos registros do banco

In [4]:
df.head(10)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,CustomerFeedback,MonthlyIncome
0,4578-PHJYZ,Male,0,Yes,Yes,52,Yes,No,DSL,No,...,Yes,No,One year,Yes,Electronic check,68.75,3482.85,No,I have been a customer with this internet prov...,6532
1,6289-CPNLD,Male,0,Yes,Yes,33,Yes,No,DSL,No,...,Yes,Yes,One year,Yes,Mailed check,73.90,2405.05,Yes,I've been a customer with this company for ove...,7634
2,2682-KEVRP,Female,1,No,No,22,Yes,No,No,No internet service,...,No internet service,No internet service,One year,Yes,Mailed check,20.05,417.00,No,I have been a customer with this company for 2...,3628
3,5697-GOMBF,Female,1,Yes,Yes,28,No,No phone service,DSL,No,...,Yes,No,Month-to-month,Yes,Electronic check,35.90,973.65,No,I have been a customer with this internet prov...,7851
4,9717-QEBGU,Male,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Electronic check,70.30,144.00,No,I have been using the fiber optic internet ser...,1691
5,6797-LNAQX,Male,0,Yes,Yes,70,Yes,Yes,Fiber optic,No,...,Yes,Yes,Two year,No,Bank transfer (automatic),98.30,6859.50,Yes,I have been a customer with this company for 7...,5487
6,3050-GBUSH,Female,0,No,No,3,no,No phone service,DSL,No,...,Yes,No,Month-to-month,Yes,Credit card (automatic),34.80,113.95,No,I have been a customer with this DSL internet ...,6382
7,8020-BWHYL,Female,1,No,No,15,Yes,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Credit card (automatic),75.30,NaN,Yes,I recently canceled my service with this provi...,353
8,6752-APNJL,Male,0,Yes,Yes,42,Yes,No,DSL,Yes,...,No,No,Month-to-month,No,Mailed check,54.50,2301.15,No,I have been a customer with this company for 4...,2436
9,1760-CAZHT,Male,0,No,Yes,25,Yes,No,No,No internet service,...,No internet service,No internet service,Month-to-month,No,Mailed check,20.80,460.20,No,I have been a customer with this company for 2...,7049

In [5]:
df.tail(10)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,CustomerFeedback,MonthlyIncome
5624,8869-LIHMK,Female,0,No,No,64,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Two year,Yes,Bank transfer (automatic),115.10,7334.05,No,I have been a loyal customer of this company f...,5342
5625,0932-YIXYU,Female,0,No,No,47,yes,No,No,No internet service,...,No internet service,No internet service,Two year,No,Credit card (automatic),20.25,1029.80,No,I have been a customer with this company for a...,9229
5626,3569-EDBPQ,Female,0,No,No,24,Yes,Yes,Fiber optic,Yes,...,No,No,Month-to-month,Yes,Electronic check,84.35,1938.05,No,I have been a customer with this fiber optic i...,7165
5627,8645-KOMJQ,Male,0,Yes,Yes,69,Yes,Yes,DSL,No,...,Yes,Yes,Two year,Yes,Bank transfer (automatic),81.95,5601.40,No,I have been a loyal customer with this company...,411
5628,0786-IVLAW,Female,1,No,No,66,Yes,Yes,Fiber optic,No,...,Yes,Yes,One year,No,Bank transfer (automatic),108.10,7238.60,No,I have been a customer with this company for 6...,5113
5629,8909-BOLNL,Male,0,No,No,3,Yes,No,No,No internet service,...,No internet service,No internet service,One year,No,Mailed check,21.20,52.05,No,I have been a customer with this company for 3...,8354
5630,2832-KJCRD,Female,0,No,No,38,Yes,Yes,Fiber optic,No,...,Yes,Yes,Month-to-month,Yes,Electronic check,103.65,3988.50,No,I have been a customer with this company for 3...,9308
5631,7975-JMZNT,Male,0,Yes,No,66,Yes,Yes,DSL,Yes,...,Yes,Yes,Two year,No,Bank transfer (automatic),91.70,6075.90,No,I have been a customer with this DSL internet ...,2113
5632,4250-ZBWLV,Male,0,No,No,68,Yes,Yes,Fiber optic,No,...,Yes,Yes,One year,No,Electronic check,108.45,7176.55,Yes,I have been a customer with this company for o...,3904
5633,3915-ODIYG,Male,1,No,No,60,Yes,Yes,DSL,Yes,...,No,Yes,One year,Yes,Electronic check,71.75,4374.55,No,I have been a loyal customer of this internet ...,3016

### Conhecendo o tipo dos dados e variaveis

In [6]:
df.dtypes
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5634 entries, 0 to 5633
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        5634 non-null   str
 1   gender            5634 non-null   str
 2   SeniorCitizen     5634 non-null   int64
 3   Partner           5634 non-null   str
 4   Dependents        5634 non-null   str
 5   tenure            5634 non-null   str
 6   PhoneService      5634 non-null   str
 7   MultipleLines     5634 non-null   str
 8   InternetService   5634 non-null   str
 9   OnlineSecurity    5634 non-null   str
 10  OnlineBackup      5634 non-null   str
 11  DeviceProtection  5634 non-null   str
 12  TechSupport       5634 non-null   str
 13  StreamingTV       5634 non-null   str
 14  StreamingMovies   5634 non-null   str
 15  Contract          5634 non-null   str
 16  PaperlessBilling  5634 non-null   str
 17  PaymentMethod     5634 non-null   str
 18  MonthlyCharges    5634 non-null   float64
 19  TotalCharges      5356 non-null   float64
 20  Churn             5634 non-null   str
 21  CustomerFeedback  5634 non-null   str
 22  MonthlyIncome     5634 non-null   int64
dtypes: float64(2), int64(2), str(19)
memory usage: 4.0 MB

### dicionario de dados

In [7]:
dicionario_dados = {
    "Variável Original": [
        "customerID", "gender", "SeniorCitizen", "Partner", "Dependents", "tenure",
        "PhoneService", "MultipleLines", "InternetService", "OnlieSecurity", "OnlineBackup",
        "DeviceProtection", "TechSupport", "StreamingTV", "StreamingMovies", "Contract",
        "PaperlessBilling", "PaymentMethod", "MonthlyCharges", "TotalCharges", "Churn",
        "CustomerFeedback", "MonthlyIncome"
    ],
    "Variável Traduzida": [
        "clienteID", "genero", "idoso", "conjuge", "dependentes", "tempoDeServiço",
        "serviçoTelefonico", "multiplasLinhasTelefonicas", "serviçoDeInternet",
        "segurançaOnline", "backupOnline", "proteçaoDeDispositivo", "suporteTecnico",
        "streamingTV", "streamingDeFilmes", "contrato", "faturaDigital",
        "metodoDePagamento", "mensalidade", "totalDeEncargos", "cancelamento",
        "feedbackDoCliente", "rendaMensal"
    ]
}

traducao = dict(zip(
    dicionario_dados["Variável Original"],
    dicionario_dados["Variável Traduzida"]
))

df = df.rename(columns=traducao)

# Transforma o dicionário em um DataFrame do Pandas
df_dicionario = pd.DataFrame(dicionario_dados)

print(df_dicionario.to_string(index=False))

Variável Original         Variável Traduzida
       customerID                  clienteID
           gender                     genero
    SeniorCitizen                      idoso
          Partner                    conjuge
       Dependents                dependentes
           tenure             tempoDeServiço
     PhoneService          serviçoTelefonico
    MultipleLines multiplasLinhasTelefonicas
  InternetService          serviçoDeInternet
    OnlieSecurity            segurançaOnline
     OnlineBackup               backupOnline
 DeviceProtection      proteçaoDeDispositivo
      TechSupport             suporteTecnico
      StreamingTV                streamingTV
  StreamingMovies          streamingDeFilmes
         Contract                   contrato
 PaperlessBilling              faturaDigital
    PaymentMethod          metodoDePagamento
   MonthlyCharges                mensalidade
     TotalCharges            totalDeEncargos
            Churn               cancelamento
 CustomerFeedback          feedbackDoCliente
    MonthlyIncome                rendaMensal

In [ ]:
df["clienteID"] = df["clienteID"].astype("string")
df["genero"] = df["genero"].astype("category")
df["idoso"] = df["idoso"].astype("bool")
df["conjuge"] = df["conjuge"].astype("bool")
df["dependentes"] = df["dependentes"].astype("bool")
df["tempoDeServiço"] = pd.to_numeric(
    df["tempoDeServiço"].replace("unknown", pd.NA),
    errors="coerce"
).astype("Int8")
df["serviçoTelefonico"] = df["serviçoTelefonico"].astype("category")

In [12]:
print("Valor mínimo:", df["tempoDeServiço"].min())
print("Valor máximo:", df["tempoDeServiço"].max())

Valor mínimo: 0
Valor máximo: 72

In [13]:
df.info(verbose=True)

<class 'pandas.DataFrame'>
RangeIndex: 5634 entries, 0 to 5633
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   clienteID                   5634 non-null   string
 1   genero                      5634 non-null   category
 2   idoso                       5634 non-null   bool
 3   conjuge                     5634 non-null   bool
 4   dependentes                 5634 non-null   bool
 5   tempoDeServiço              5615 non-null   Int8
 6   serviçoTelefonico           5634 non-null   category
 7   multiplasLinhasTelefonicas  5634 non-null   str
 8   serviçoDeInternet           5634 non-null   str
 9   OnlineSecurity              5634 non-null   str
 10  backupOnline                5634 non-null   str
 11  proteçaoDeDispositivo       5634 non-null   str
 12  suporteTecnico              5634 non-null   str
 13  streamingTV                 5634 non-null   str
 14  streamingDeFilmes           5634 non-null   str
 15  contrato                    5634 non-null   str
 16  faturaDigital               5634 non-null   str
 17  metodoDePagamento           5634 non-null   str
 18  mensalidade                 5634 non-null   float64
 19  totalDeEncargos             5356 non-null   float64
 20  cancelamento                5634 non-null   str
 21  feedbackDoCliente           5634 non-null   str
 22  rendaMensal                 5634 non-null   int64
dtypes: Int8(1), bool(3), category(2), float64(2), int64(1), str(13), string(1)
memory usage: 3.7 MB

## valores nulos e duplicados

In [16]:
#Nulos
df.isnull().sum()

clienteID                       0
genero                          0
idoso                           0
conjuge                         0
dependentes                     0
tempoDeServiço                 19
serviçoTelefonico               0
multiplasLinhasTelefonicas      0
serviçoDeInternet               0
OnlineSecurity                  0
backupOnline                    0
proteçaoDeDispositivo           0
suporteTecnico                  0
streamingTV                     0
streamingDeFilmes               0
contrato                        0
faturaDigital                   0
metodoDePagamento               0
mensalidade                     0
totalDeEncargos               278
cancelamento                    0
feedbackDoCliente               0
rendaMensal                     0
dtype: int64

In [17]:
df.duplicated().sum()

np.int64(0)

In [29]:
df[df["tempoDeServiço"].isnull()]

,clienteID,genero,idoso,conjuge,dependentes,tempoDeServiço,serviçoTelefonico,multiplasLinhasTelefonicas,serviçoDeInternet,OnlineSecurity,...,streamingTV,streamingDeFilmes,contrato,faturaDigital,metodoDePagamento,mensalidade,totalDeEncargos,cancelamento,feedbackDoCliente,rendaMensal
1059,7301-ABVAD,Female,False,True,True,<NA>,Yes,Yes,DSL,No,...,Yes,Yes,Two year,No,Bank transfer (automatic),86.60,6350.50,No,I have been a customer with this company for 6...,3093
1097,9651-GTSAQ,Female,False,True,True,<NA>,Yes,No,Fiber optic,Yes,...,Yes,Yes,One year,Yes,Bank transfer (automatic),106.10,NaN,Yes,I have been a customer with this company for o...,4702
1791,0135-NMXAP,Female,False,True,True,<NA>,Yes,Yes,Fiber optic,No,...,Yes,No,Month-to-month,Yes,Bank transfer (automatic),89.75,1052.40,Yes,I recently cancelled my service with this comp...,7709
1984,3892-NXAZG,Male,False,True,True,<NA>,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Two year,Yes,Credit card (automatic),114.05,8289.20,No,I have been a customer with this company for 6...,4415
2361,3934-HXCFZ,Male,False,True,True,<NA>,Yes,Yes,Fiber optic,Yes,...,Yes,No,Month-to-month,Yes,Electronic check,99.25,2186.40,Yes,I have been a customer of this fiber optic int...,9165
2372,1622-HSHSF,Female,False,True,True,<NA>,Yes,No,No,No internet service,...,No internet service,No internet service,Month-to-month,Yes,Mailed check,19.55,19.55,No,I have only been a customer with this company ...,4751
2641,6907-NZZIJ,Female,False,True,True,<NA>,Yes,Yes,Fiber optic,No,...,Yes,Yes,Month-to-month,Yes,Electronic check,99.15,3615.60,Yes,I have been a customer with this company for 3...,4701
2896,6023-GSSXW,Female,False,True,True,<NA>,Yes,No,DSL,No,...,No,Yes,Two year,Yes,Credit card (automatic),61.45,4131.20,No,I have been a customer with this company for a...,2494
2936,5688-KZTSN,Male,False,True,True,<NA>,Yes,No,No,No internet service,...,No internet service,No internet service,Month-to-month,Yes,Electronic check,20.00,288.05,Yes,I recently cancelled my service with this prov...,4749
2959,7694-VLBWQ,Male,False,True,True,<NA>,Yes,Yes,Fiber optic,No,...,Yes,Yes,One year,No,Electronic check,104.10,7040.85,Yes,I have been a customer with this company for o...,8867
3153,1619-YWUBB,Female,False,True,True,<NA>,Yes,Yes,No,No internet service,...,No internet service,No internet service,Two year,Yes,Credit card (automatic),24.95,1614.90,No,I have been a customer with this company for o...,8009
3300,9575-IWCAZ,Male,False,True,True,<NA>,Yes,Yes,No,No internet service,...,No internet service,No internet service,One year,No,Mailed check,25.10,171.00,No,I have been a customer with this company for 6...,752
3388,4702-HDRKD,Male,False,True,True,<NA>,No,No phone service,DSL,Yes,...,Yes,No,One year,Yes,Bank transfer (automatic),49.35,3321.35,No,I have been a loyal customer of this DSL inter...,198
3476,6469-QJKZW,Female,False,True,True,<NA>,Yes,No,No,No internet service,...,No internet service,No internet service,Month-to-month,No,Electronic check,20.15,91.40,No,I have been a customer with this company for 4...,1306
3515,2672-HUYVI,Female,False,True,True,<NA>,Yes,No,Fiber optic,No,...,Yes,Yes,Month-to-month,Yes,Electronic check,91.10,455.30,Yes,I recently canceled my service after being a c...,5701
3837,3274-NSDWE,Female,False,True,True,<NA>,Yes,No,No,No internet service,...,No internet service,No internet service,Two year,No,Credit card (automatic),19.60,1441.65,No,I have been a loyal customer with this company...,3753
4875,3348-CFRNX,Female,False,True,True,<NA>,Yes,No,Fiber optic,Yes,...,Yes,Yes,Month-to-month,Yes,Mailed check,92.35,2602.90,Yes,I recently made the difficult decision to canc...,1437
5324,6614-VBEGU,Female,False,True,True,<NA>,Yes,No,DSL,No,...,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),69.45,1614.05,No,I have been a customer with this internet prov...,3688
5328,1293-BSEUN,Female,False,True,True,<NA>,Yes,No,No,No internet service,...,No internet service,No internet service,Two year,Yes,Mailed check,20.70,1482.30,No,I have been a customer with this company for 6...,3396

In [44]:
#descobrindo motivo dos valores nulos
df[df["tempoDeServiço"].isnull()]["contrato"].value_counts()

contrato
Month-to-month    9
Two year          6
One year          4
Name: count, dtype: int64

In [ ]:
# registros nulos de "totalDeEncargos" e os motivos
df[df["totalDeEncargos"].isnull()][["tempoDeServiço", "mensalidade", "totalDeEncargos","contrato", "cancelamento",]]

,tempoDeServiço,mensalidade,totalDeEncargos,contrato,cancelamento
7,15,75.30,NaN,Month-to-month,Yes
49,1,74.90,NaN,Month-to-month,Yes
64,4,88.95,NaN,Month-to-month,Yes
79,43,109.55,NaN,One year,Yes
122,46,54.35,NaN,Two year,Yes
...,...,...,...,...,...
5535,55,90.45,NaN,Month-to-month,No
5546,4,50.70,NaN,Month-to-month,Yes
5552,0,73.35,NaN,Two year,No
5592,45,34.20,NaN,One year,No
5594,2,69.65,NaN,Month-to-month,Yes

In [ ]:
df[]