## Leitura do dataset CSV

## Importando bibliotecas
- Utilização de bibliotecas em todas as etapas (Bronze, Prata e Gold)

In [59]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv("history.csv")

## Conhecendo o Dataset **(Bronze)**
- Primeiros e últimos registros do banco

In [46]:
#primeira vizualização do dataframe
df.head(10)

,clienteID,genero,idoso,conjuge,dependentes,tempoDeServiço,serviçoTelefonico,multiplasLinhasTelefonicas,serviçoDeInternet,segurançaOnline,...,streamingTV,streamingDeFilmes,contrato,faturaDigital,metodoDePagamento,mensalidade,totalDeEncargos,cancelamento,feedbackDoCliente,rendaMensal
0,4578-PHJYZ,Male,False,True,True,52,Yes,Yes,DSL,No,...,Yes,No,One year,True,Electronic check,68.750000,3482.85,True,I have been a customer with this internet prov...,6532
1,6289-CPNLD,Male,False,True,True,33,Yes,Yes,DSL,No,...,Yes,Yes,One year,True,Mailed check,73.900002,2405.05,True,I've been a customer with this company for ove...,7634
2,2682-KEVRP,Female,True,True,True,22,Yes,Yes,No,No internet service,...,No internet service,No internet service,One year,True,Mailed check,20.049999,417.00,True,I have been a customer with this company for 2...,3628
3,5697-GOMBF,Female,True,True,True,28,No,No,DSL,No,...,Yes,No,Month-to-month,True,Electronic check,35.900002,973.65,True,I have been a customer with this internet prov...,7851
4,9717-QEBGU,Male,False,True,True,2,Yes,Yes,Fiber optic,No,...,No,No,Month-to-month,True,Electronic check,70.300003,144.00,True,I have been using the fiber optic internet ser...,1691
5,6797-LNAQX,Male,False,True,True,70,Yes,Yes,Fiber optic,No,...,Yes,Yes,Two year,True,Bank transfer (automatic),98.300003,6859.50,True,I have been a customer with this company for 7...,5487
6,3050-GBUSH,Female,False,True,True,3,no,no,DSL,No,...,Yes,No,Month-to-month,True,Credit card (automatic),34.799999,113.95,True,I have been a customer with this DSL internet ...,6382
7,8020-BWHYL,Female,True,True,True,15,Yes,Yes,Fiber optic,No,...,No,No,Month-to-month,True,Credit card (automatic),75.300003,NaN,True,I recently canceled my service with this provi...,353
8,6752-APNJL,Male,False,True,True,42,Yes,Yes,DSL,Yes,...,No,No,Month-to-month,True,Mailed check,54.500000,2301.15,True,I have been a customer with this company for 4...,2436
9,1760-CAZHT,Male,False,True,True,25,Yes,Yes,No,No internet service,...,No internet service,No internet service,Month-to-month,True,Mailed check,20.799999,460.20,True,I have been a customer with this company for 2...,7049

In [6]:
df.tail(10)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,CustomerFeedback,MonthlyIncome
5624,8869-LIHMK,Female,0,No,No,64,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Two year,Yes,Bank transfer (automatic),115.10,7334.05,No,I have been a loyal customer of this company f...,5342
5625,0932-YIXYU,Female,0,No,No,47,yes,No,No,No internet service,...,No internet service,No internet service,Two year,No,Credit card (automatic),20.25,1029.80,No,I have been a customer with this company for a...,9229
5626,3569-EDBPQ,Female,0,No,No,24,Yes,Yes,Fiber optic,Yes,...,No,No,Month-to-month,Yes,Electronic check,84.35,1938.05,No,I have been a customer with this fiber optic i...,7165
5627,8645-KOMJQ,Male,0,Yes,Yes,69,Yes,Yes,DSL,No,...,Yes,Yes,Two year,Yes,Bank transfer (automatic),81.95,5601.40,No,I have been a loyal customer with this company...,411
5628,0786-IVLAW,Female,1,No,No,66,Yes,Yes,Fiber optic,No,...,Yes,Yes,One year,No,Bank transfer (automatic),108.10,7238.60,No,I have been a customer with this company for 6...,5113
5629,8909-BOLNL,Male,0,No,No,3,Yes,No,No,No internet service,...,No internet service,No internet service,One year,No,Mailed check,21.20,52.05,No,I have been a customer with this company for 3...,8354
5630,2832-KJCRD,Female,0,No,No,38,Yes,Yes,Fiber optic,No,...,Yes,Yes,Month-to-month,Yes,Electronic check,103.65,3988.50,No,I have been a customer with this company for 3...,9308
5631,7975-JMZNT,Male,0,Yes,No,66,Yes,Yes,DSL,Yes,...,Yes,Yes,Two year,No,Bank transfer (automatic),91.70,6075.90,No,I have been a customer with this DSL internet ...,2113
5632,4250-ZBWLV,Male,0,No,No,68,Yes,Yes,Fiber optic,No,...,Yes,Yes,One year,No,Electronic check,108.45,7176.55,Yes,I have been a customer with this company for o...,3904
5633,3915-ODIYG,Male,1,No,No,60,Yes,Yes,DSL,Yes,...,No,Yes,One year,Yes,Electronic check,71.75,4374.55,No,I have been a loyal customer of this internet ...,3016

### Dicionario dos dados do dataframe

| Coluna           | Tradução                 | Definição resumida                                        |
| ---------------- | ------------------------ | --------------------------------------------------------- |
| customerID       | ID do cliente            | Código único de identificação do cliente.                 |
| gender           | Gênero                   | Gênero do cliente.                                        |
| SeniorCitizen    | Cidadão idoso            | Indica se o cliente é idoso (1 = sim, 0 = não).           |
| Partner          | Parceiro(a)              | Indica se o cliente possui companheiro(a).                |
| Dependents       | Dependentes              | Indica se o cliente possui dependentes.                   |
| tenure           | Tempo de permanência     | Tempo de relacionamento com a empresa, em meses.          |
| PhoneService     | Serviço telefônico       | Indica se o cliente possui telefone contratado.           |
| MultipleLines    | Múltiplas linhas         | Indica se possui mais de uma linha telefônica.            |
| InternetService  | Serviço de internet      | Tipo de serviço de internet contratado.                   |
| OnlineSecurity   | Segurança online         | Indica se possui serviço de segurança digital.            |
| OnlineBackup     | Backup online            | Indica se possui cópia de segurança de arquivos na nuvem. |
| DeviceProtection | Proteção de dispositivos | Indica se possui proteção para seus dispositivos.         |
| TechSupport      | Suporte técnico          | Indica se possui assistência técnica contratada.          |
| StreamingTV      | Transmissão de TV        | Indica se possui serviço de streaming de televisão.       |
| StreamingMovies  | Streaming de filmes      | Indica se possui serviço de streaming de filmes.          |
| Contract         | Contrato                 | Tipo e duração do contrato do cliente.                    |
| PaperlessBilling | Faturamento sem papel    | Indica se recebe a fatura digitalmente.                   |
| PaymentMethod    | Método de pagamento      | Forma utilizada para pagar pelos serviços.                |
| MonthlyCharges   | Cobranças mensais        | Valor cobrado mensalmente pelos serviços.                 |
| TotalCharges     | Cobranças totais         | Valor total acumulado cobrado do cliente.                 |
| Churn            | Cancelamento             | Indica se o cliente cancelou o serviço.                   |
| CustomerFeedback | Feedback do cliente      | Comentário do cliente sobre sua experiência.              |
| MonthlyIncome    | Renda mensal             | Valor da renda mensal do cliente.                         |

### Conhecendo o tipo dos dados e variaveis

In [7]:
df.dtypes
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5634 entries, 0 to 5633
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        5634 non-null   str
 1   gender            5634 non-null   str
 2   SeniorCitizen     5634 non-null   int64
 3   Partner           5634 non-null   str
 4   Dependents        5634 non-null   str
 5   tenure            5634 non-null   str
 6   PhoneService      5634 non-null   str
 7   MultipleLines     5634 non-null   str
 8   InternetService   5634 non-null   str
 9   OnlineSecurity    5634 non-null   str
 10  OnlineBackup      5634 non-null   str
 11  DeviceProtection  5634 non-null   str
 12  TechSupport       5634 non-null   str
 13  StreamingTV       5634 non-null   str
 14  StreamingMovies   5634 non-null   str
 15  Contract          5634 non-null   str
 16  PaperlessBilling  5634 non-null   str
 17  PaymentMethod     5634 non-null   str
 18  MonthlyCharges    5634 non-null   float64
 19  TotalCharges      5356 non-null   float64
 20  Churn             5634 non-null   str
 21  CustomerFeedback  5634 non-null   str
 22  MonthlyIncome     5634 non-null   int64
dtypes: float64(2), int64(2), str(19)
memory usage: 1012.5 KB

### dicionario de dados

Traduzindo colunas do banco de dados com dicionario de dados

In [13]:
dicionario_dados = {
    "Variável Original": [
        "customerID", "gender", "SeniorCitizen", "Partner", "Dependents", "tenure",
        "PhoneService", "MultipleLines", "InternetService", "OnlineSecurity", "OnlineBackup",
        "DeviceProtection", "TechSupport", "StreamingTV", "StreamingMovies", "Contract",
        "PaperlessBilling", "PaymentMethod", "MonthlyCharges", "TotalCharges", "Churn",
        "CustomerFeedback", "MonthlyIncome"
    ],
    "Variável Traduzida": [
        "clienteID", "genero", "idoso", "conjuge", "dependentes", "tempoDeServiço",
        "serviçoTelefonico", "multiplasLinhasTelefonicas", "serviçoDeInternet",
        "segurançaOnline", "backupOnline", "proteçaoDeDispositivo", "suporteTecnico",
        "streamingTV", "streamingDeFilmes", "contrato", "faturaDigital",
        "metodoDePagamento", "mensalidade", "totalDeEncargos", "cancelamento",
        "feedbackDoCliente", "rendaMensal"
    ]
}

traducao = dict(zip(
    dicionario_dados["Variável Original"],
    dicionario_dados["Variável Traduzida"]
))

df = df.rename(columns=traducao)

# Transforma o dicionário em um DataFrame do Pandas
df_dicionario = pd.DataFrame(dicionario_dados)

print(df_dicionario.to_string(index=False))

Variável Original         Variável Traduzida
       customerID                  clienteID
           gender                     genero
    SeniorCitizen                      idoso
          Partner                    conjuge
       Dependents                dependentes
           tenure             tempoDeServiço
     PhoneService          serviçoTelefonico
    MultipleLines multiplasLinhasTelefonicas
  InternetService          serviçoDeInternet
   OnlineSecurity            segurançaOnline
     OnlineBackup               backupOnline
 DeviceProtection      proteçaoDeDispositivo
      TechSupport             suporteTecnico
      StreamingTV                streamingTV
  StreamingMovies          streamingDeFilmes
         Contract                   contrato
 PaperlessBilling              faturaDigital
    PaymentMethod          metodoDePagamento
   MonthlyCharges                mensalidade
     TotalCharges            totalDeEncargos
            Churn               cancelamento
 CustomerFeedback          feedbackDoCliente
    MonthlyIncome                rendaMensal

Trocando tipos de variveis

In [44]:
df["clienteID"] = df["clienteID"].astype("string")

df["genero"] = df["genero"].astype("category")

df["idoso"] = df["idoso"].astype("bool")

df["conjuge"] = df["conjuge"].astype("bool")

df["dependentes"] = df["dependentes"].astype("bool")

df["tempoDeServiço"] = pd.to_numeric(
    df["tempoDeServiço"].replace("unknown", pd.NA),
    errors="coerce"
).astype("Int8")

df["serviçoTelefonico"] = df["serviçoTelefonico"].astype("category")

df["multiplasLinhasTelefonicas"] = df["serviçoTelefonico"].astype("category")

df["serviçoDeInternet"] = df["serviçoDeInternet"].astype("category")

df["segurançaOnline"] = df["segurançaOnline"].astype("category")

df["backupOnline"] = df["backupOnline"].astype("category")

df["proteçaoDeDispositivo"] = df["proteçaoDeDispositivo"].astype("category")

df["suporteTecnico"] = df["suporteTecnico"].astype("category")

df["streamingTV"] = df["streamingTV"].astype("category")

df["streamingDeFilmes"] = df["streamingDeFilmes"].astype("category")

df["contrato"] = df["contrato"].astype("category")

df["faturaDigital"] = df["faturaDigital"].astype("bool")

df["metodoDePagamento"] = df["metodoDePagamento"].astype("category")

df["mensalidade"] = df["mensalidade"].astype("float32")

df["cancelamento"] = df["cancelamento"].astype("bool")

df["feedbackDoCliente"] = df["feedbackDoCliente"].astype("string")

df["rendaMensal"] = df["rendaMensal"].astype("int16")

In [37]:
df.info(verbose=True)

<class 'pandas.DataFrame'>
RangeIndex: 5634 entries, 0 to 5633
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   clienteID                   5634 non-null   string
 1   genero                      5634 non-null   category
 2   idoso                       5634 non-null   bool
 3   conjuge                     5634 non-null   bool
 4   dependentes                 5634 non-null   bool
 5   tempoDeServiço              5615 non-null   Int8
 6   serviçoTelefonico           5634 non-null   category
 7   multiplasLinhasTelefonicas  5634 non-null   category
 8   serviçoDeInternet           5634 non-null   category
 9   segurançaOnline             5634 non-null   category
 10  backupOnline                5634 non-null   category
 11  proteçaoDeDispositivo       5634 non-null   category
 12  suporteTecnico              5634 non-null   category
 13  streamingTV                 5634 non-null   category
 14  streamingDeFilmes           5634 non-null   category
 15  contrato                    5634 non-null   category
 16  faturaDigital               5634 non-null   bool
 17  metodoDePagamento           5634 non-null   category
 18  mensalidade                 5634 non-null   float64
 19  totalDeEncargos             5356 non-null   float64
 20  cancelamento                5634 non-null   bool
 21  feedbackDoCliente           5634 non-null   string
 22  rendaMensal                 5634 non-null   int16
dtypes: Int8(1), bool(5), category(12), float64(2), int16(1), string(2)
memory usage: 292.0 KB

In [38]:
df["rendaMensal"].unique()

array([6532, 7634, 3628, ..., 9308, 3904, 3016],
      shape=(4307,), dtype=int16)

In [39]:
df.isnull().sum()

clienteID                       0
genero                          0
idoso                           0
conjuge                         0
dependentes                     0
tempoDeServiço                 19
serviçoTelefonico               0
multiplasLinhasTelefonicas      0
serviçoDeInternet               0
segurançaOnline                 0
backupOnline                    0
proteçaoDeDispositivo           0
suporteTecnico                  0
streamingTV                     0
streamingDeFilmes               0
contrato                        0
faturaDigital                   0
metodoDePagamento               0
mensalidade                     0
totalDeEncargos               278
cancelamento                    0
feedbackDoCliente               0
rendaMensal                     0
dtype: int64

In [40]:
df["totalDeEncargos"].head(60)

0     3482.85
1     2405.05
2      417.00
3      973.65
4      144.00
5     6859.50
6      113.95
7         NaN
8     2301.15
9      460.20
10     478.75
11     278.40
12      50.45
13    2192.90
14    2369.70
15    2351.45
16    6341.45
17    7323.15
18      70.10
19      55.70
20    4415.75
21    7854.15
22      70.30
23    2386.85
24    3361.05
25    3673.60
26    1205.05
27    7321.05
28    3186.70
29    5305.05
30      25.25
31     207.40
32     818.05
33     403.35
34    1111.85
35      20.05
36      20.05
37    3942.45
38    1182.55
39    7719.50
40     246.50
41    1211.65
42    3252.00
43    2511.30
44     702.00
45    7372.65
46    5976.90
47    5832.00
48    7156.20
49        NaN
50     231.80
51     592.65
52    5706.20
53      79.80
54    1356.70
55     662.95
56     635.90
57    8033.10
58    6034.85
59     255.25
Name: totalDeEncargos, dtype: float64

In [64]:
for i, linha in df.iterrows():
    if linha.iloc[19:20].isnull().any():
        print(f"Linha: {i} | totalDeEncargos: {linha['totalDeEncargos']}")

Linha: 49 | totalDeEncargos: nan
Linha: 64 | totalDeEncargos: nan
Linha: 79 | totalDeEncargos: nan
Linha: 122 | totalDeEncargos: nan
Linha: 138 | totalDeEncargos: nan
Linha: 139 | totalDeEncargos: nan
Linha: 143 | totalDeEncargos: nan
Linha: 162 | totalDeEncargos: nan
Linha: 176 | totalDeEncargos: nan
Linha: 188 | totalDeEncargos: nan
Linha: 193 | totalDeEncargos: nan
Linha: 237 | totalDeEncargos: nan
Linha: 257 | totalDeEncargos: nan
Linha: 275 | totalDeEncargos: nan
Linha: 305 | totalDeEncargos: nan
Linha: 317 | totalDeEncargos: nan
Linha: 326 | totalDeEncargos: nan
Linha: 335 | totalDeEncargos: nan
Linha: 345 | totalDeEncargos: nan
Linha: 346 | totalDeEncargos: nan
Linha: 347 | totalDeEncargos: nan
Linha: 351 | totalDeEncargos: nan
Linha: 369 | totalDeEncargos: nan
Linha: 412 | totalDeEncargos: nan
Linha: 437 | totalDeEncargos: nan
Linha: 458 | totalDeEncargos: nan
Linha: 463 | totalDeEncargos: nan
Linha: 502 | totalDeEncargos: nan
Linha: 511 | totalDeEncargos: nan
Linha: 514 | totalDeEncargos: nan
Linha: 582 | totalDeEncargos: nan
Linha: 589 | totalDeEncargos: nan
Linha: 612 | totalDeEncargos: nan
Linha: 623 | totalDeEncargos: nan
Linha: 627 | totalDeEncargos: nan
Linha: 638 | totalDeEncargos: nan
Linha: 649 | totalDeEncargos: nan
Linha: 660 | totalDeEncargos: nan
Linha: 676 | totalDeEncargos: nan
Linha: 678 | totalDeEncargos: nan
Linha: 682 | totalDeEncargos: nan
Linha: 750 | totalDeEncargos: nan
Linha: 751 | totalDeEncargos: nan
Linha: 761 | totalDeEncargos: nan
Linha: 790 | totalDeEncargos: nan
Linha: 833 | totalDeEncargos: nan
Linha: 834 | totalDeEncargos: nan
Linha: 843 | totalDeEncargos: nan
Linha: 848 | totalDeEncargos: nan
Linha: 865 | totalDeEncargos: nan
Linha: 887 | totalDeEncargos: nan
Linha: 899 | totalDeEncargos: nan
Linha: 911 | totalDeEncargos: nan
Linha: 974 | totalDeEncargos: nan
Linha: 985 | totalDeEncargos: nan
Linha: 1028 | totalDeEncargos: nan
Linha: 1034 | totalDeEncargos: nan
Linha: 1044 | totalDeEncargos: nan
Linha: 1075 | totalDeEncargos: nan
Linha: 1084 | totalDeEncargos: nan
Linha: 1092 | totalDeEncargos: nan
Linha: 1097 | totalDeEncargos: nan
Linha: 1150 | totalDeEncargos: nan
Linha: 1189 | totalDeEncargos: nan
Linha: 1194 | totalDeEncargos: nan
Linha: 1230 | totalDeEncargos: nan
Linha: 1296 | totalDeEncargos: nan
Linha: 1300 | totalDeEncargos: nan
Linha: 1307 | totalDeEncargos: nan
Linha: 1330 | totalDeEncargos: nan
Linha: 1353 | totalDeEncargos: nan
Linha: 1360 | totalDeEncargos: nan
Linha: 1409 | totalDeEncargos: nan
Linha: 1433 | totalDeEncargos: nan
Linha: 1446 | totalDeEncargos: nan
Linha: 1460 | totalDeEncargos: nan
Linha: 1480 | totalDeEncargos: nan
Linha: 1488 | totalDeEncargos: nan
Linha: 1489 | totalDeEncargos: nan
Linha: 1537 | totalDeEncargos: nan
Linha: 1575 | totalDeEncargos: nan
Linha: 1591 | totalDeEncargos: nan
Linha: 1603 | totalDeEncargos: nan
Linha: 1622 | totalDeEncargos: nan
Linha: 1627 | totalDeEncargos: nan
Linha: 1662 | totalDeEncargos: nan
Linha: 1696 | totalDeEncargos: nan
Linha: 1722 | totalDeEncargos: nan
Linha: 1730 | totalDeEncargos: nan
Linha: 1741 | totalDeEncargos: nan
Linha: 1755 | totalDeEncargos: nan
Linha: 1767 | totalDeEncargos: nan
Linha: 1768 | totalDeEncargos: nan
Linha: 1773 | totalDeEncargos: nan
Linha: 1789 | totalDeEncargos: nan
Linha: 1812 | totalDeEncargos: nan
Linha: 1819 | totalDeEncargos: nan
Linha: 1826 | totalDeEncargos: nan
Linha: 1914 | totalDeEncargos: nan
Linha: 1928 | totalDeEncargos: nan
Linha: 1943 | totalDeEncargos: nan
Linha: 2026 | totalDeEncargos: nan
Linha: 2044 | totalDeEncargos: nan
Linha: 2066 | totalDeEncargos: nan
Linha: 2098 | totalDeEncargos: nan
Linha: 2105 | totalDeEncargos: nan
Linha: 2108 | totalDeEncargos: nan
Linha: 2122 | totalDeEncargos: nan
Linha: 2137 | totalDeEncargos: nan
Linha: 2145 | totalDeEncargos: nan
Linha: 2159 | totalDeEncargos: nan
Linha: 2169 | totalDeEncargos: nan
Linha: 2204 | totalDeEncargos: nan
Linha: 2239 | totalDeEncargos: nan
Linha: 2241 | totalDeEncargos: nan
Linha: 2242 | totalDeEncargos: nan
Linha: 2291 | totalDeEncargos: nan
Linha: 2322 | totalDeEncargos: nan
Linha: 2338 | totalDeEncargos: nan
Linha: 2378 | totalDeEncargos: nan
Linha: 2382 | totalDeEncargos: nan
Linha: 2394 | totalDeEncargos: nan
Linha: 2406 | totalDeEncargos: nan
Linha: 2420 | totalDeEncargos: nan
Linha: 2440 | totalDeEncargos: nan
Linha: 2448 | totalDeEncargos: nan
Linha: 2472 | totalDeEncargos: nan
Linha: 2476 | totalDeEncargos: nan
Linha: 2526 | totalDeEncargos: nan
Linha: 2529 | totalDeEncargos: nan
Linha: 2623 | totalDeEncargos: nan
Linha: 2627 | totalDeEncargos: nan
Linha: 2631 | totalDeEncargos: nan
Linha: 2637 | totalDeEncargos: nan
Linha: 2644 | totalDeEncargos: nan
Linha: 2645 | totalDeEncargos: nan
Linha: 2669 | totalDeEncargos: nan
Linha: 2691 | totalDeEncargos: nan
Linha: 2705 | totalDeEncargos: nan
Linha: 2711 | totalDeEncargos: nan
Linha: 2762 | totalDeEncargos: nan
Linha: 2801 | totalDeEncargos: nan
Linha: 2804 | totalDeEncargos: nan
Linha: 2807 | totalDeEncargos: nan
Linha: 2864 | totalDeEncargos: nan
Linha: 2883 | totalDeEncargos: nan
Linha: 2888 | totalDeEncargos: nan
Linha: 2899 | totalDeEncargos: nan
Linha: 2914 | totalDeEncargos: nan
Linha: 2917 | totalDeEncargos: nan
Linha: 2983 | totalDeEncargos: nan
Linha: 2985 | totalDeEncargos: nan
Linha: 3017 | totalDeEncargos: nan
Linha: 3078 | totalDeEncargos: nan
Linha: 3085 | totalDeEncargos: nan
Linha: 3100 | totalDeEncargos: nan
Linha: 3110 | totalDeEncargos: nan
Linha: 3112 | totalDeEncargos: nan
Linha: 3122 | totalDeEncargos: nan
Linha: 3164 | totalDeEncargos: nan
Linha: 3201 | totalDeEncargos: nan
Linha: 3219 | totalDeEncargos: nan
Linha: 3221 | totalDeEncargos: nan
Linha: 3279 | totalDeEncargos: nan
Linha: 3280 | totalDeEncargos: nan
Linha: 3293 | totalDeEncargos: nan
Linha: 3299 | totalDeEncargos: nan
Linha: 3306 | totalDeEncargos: nan
Linha: 3326 | totalDeEncargos: nan
Linha: 3328 | totalDeEncargos: nan
Linha: 3350 | totalDeEncargos: nan
Linha: 3351 | totalDeEncargos: nan
Linha: 3386 | totalDeEncargos: nan
Linha: 3387 | totalDeEncargos: nan
Linha: 3392 | totalDeEncargos: nan
Linha: 3424 | totalDeEncargos: nan
Linha: 3483 | totalDeEncargos: nan
Linha: 3535 | totalDeEncargos: nan
Linha: 3568 | totalDeEncargos: nan
Linha: 3621 | totalDeEncargos: nan
Linha: 3632 | totalDeEncargos: nan
Linha: 3634 | totalDeEncargos: nan
Linha: 3635 | totalDeEncargos: nan
Linha: 3652 | totalDeEncargos: nan
Linha: 3664 | totalDeEncargos: nan
Linha: 3711 | totalDeEncargos: nan
Linha: 3716 | totalDeEncargos: nan
Linha: 3727 | totalDeEncargos: nan
Linha: 3731 | totalDeEncargos: nan
Linha: 3763 | totalDeEncargos: nan
Linha: 3797 | totalDeEncargos: nan
Linha: 3804 | totalDeEncargos: nan
Linha: 3814 | totalDeEncargos: nan
Linha: 3818 | totalDeEncargos: nan
Linha: 3824 | totalDeEncargos: nan
Linha: 3840 | totalDeEncargos: nan
Linha: 3890 | totalDeEncargos: nan
Linha: 3922 | totalDeEncargos: nan
Linha: 3925 | totalDeEncargos: nan
Linha: 3927 | totalDeEncargos: nan
Linha: 3934 | totalDeEncargos: nan
Linha: 3987 | totalDeEncargos: nan
Linha: 4006 | totalDeEncargos: nan
Linha: 4040 | totalDeEncargos: nan
Linha: 4042 | totalDeEncargos: nan
Linha: 4047 | totalDeEncargos: nan
Linha: 4060 | totalDeEncargos: nan
Linha: 4061 | totalDeEncargos: nan
Linha: 4096 | totalDeEncargos: nan
Linha: 4109 | totalDeEncargos: nan
Linha: 4132 | totalDeEncargos: nan
Linha: 4176 | totalDeEncargos: nan
Linha: 4200 | totalDeEncargos: nan
Linha: 4206 | totalDeEncargos: nan
Linha: 4207 | totalDeEncargos: nan
Linha: 4249 | totalDeEncargos: nan
Linha: 4258 | totalDeEncargos: nan
Linha: 4263 | totalDeEncargos: nan
Linha: 4278 | totalDeEncargos: nan
Linha: 4293 | totalDeEncargos: nan
Linha: 4324 | totalDeEncargos: nan
Linha: 4354 | totalDeEncargos: nan
Linha: 4378 | totalDeEncargos: nan
Linha: 4448 | totalDeEncargos: nan
Linha: 4458 | totalDeEncargos: nan
Linha: 4467 | totalDeEncargos: nan
Linha: 4519 | totalDeEncargos: nan
Linha: 4535 | totalDeEncargos: nan
Linha: 4552 | totalDeEncargos: nan
Linha: 4559 | totalDeEncargos: nan
Linha: 4560 | totalDeEncargos: nan
Linha: 4564 | totalDeEncargos: nan
Linha: 4565 | totalDeEncargos: nan
Linha: 4579 | totalDeEncargos: nan
Linha: 4623 | totalDeEncargos: nan
Linha: 4624 | totalDeEncargos: nan
Linha: 4664 | totalDeEncargos: nan
Linha: 4667 | totalDeEncargos: nan
Linha: 4726 | totalDeEncargos: nan
Linha: 4727 | totalDeEncargos: nan
Linha: 4732 | totalDeEncargos: nan
Linha: 4734 | totalDeEncargos: nan
Linha: 4741 | totalDeEncargos: nan
Linha: 4771 | totalDeEncargos: nan
Linha: 4774 | totalDeEncargos: nan
Linha: 4810 | totalDeEncargos: nan
Linha: 4851 | totalDeEncargos: nan
Linha: 4872 | totalDeEncargos: nan
Linha: 4898 | totalDeEncargos: nan
Linha: 4916 | totalDeEncargos: nan
Linha: 4991 | totalDeEncargos: nan
Linha: 4999 | totalDeEncargos: nan
Linha: 5004 | totalDeEncargos: nan
Linha: 5025 | totalDeEncargos: nan
Linha: 5038 | totalDeEncargos: nan
Linha: 5044 | totalDeEncargos: nan
Linha: 5052 | totalDeEncargos: nan
Linha: 5080 | totalDeEncargos: nan
Linha: 5087 | totalDeEncargos: nan
Linha: 5095 | totalDeEncargos: nan
Linha: 5116 | totalDeEncargos: nan
Linha: 5164 | totalDeEncargos: nan
Linha: 5173 | totalDeEncargos: nan
Linha: 5175 | totalDeEncargos: nan
Linha: 5188 | totalDeEncargos: nan
Linha: 5304 | totalDeEncargos: nan
Linha: 5350 | totalDeEncargos: nan
Linha: 5378 | totalDeEncargos: nan
Linha: 5502 | totalDeEncargos: nan
Linha: 5505 | totalDeEncargos: nan
Linha: 5515 | totalDeEncargos: nan
Linha: 5529 | totalDeEncargos: nan
Linha: 5535 | totalDeEncargos: nan
Linha: 5546 | totalDeEncargos: nan
Linha: 5552 | totalDeEncargos: nan
Linha: 5592 | totalDeEncargos: nan
Linha: 5594 | totalDeEncargos: nan

In [70]:
# Filtra apenas as linhas onde 'totalDeEncargos' é nulo (NaN)
nulos = df[df['totalDeEncargos'].isnull()]

# Mostra o resultado na tela
print(nulos[['tempoDeServiço', 'totalDeEncargos', 'mensalidade']])

      tempoDeServiço  totalDeEncargos  mensalidade
79                43              NaN   109.550003
122               46              NaN    54.349998
138               36              NaN    20.850000
139               11              NaN    19.250000
143                1              NaN    49.650002
...              ...              ...          ...
5535              55              NaN    90.449997
5546               4              NaN    50.700001
5552               0              NaN    73.349998
5592              45              NaN    34.200001
5594               2              NaN    69.650002

[275 rows x 3 columns]

In [52]:
# Filtra apenas as linhas onde 'tempoDeServiço' é nulo (NaN)
nulos = df[df['tempoDeServiço'].isnull()]

# Mostra o resultado na tela
print(nulos[['tempoDeServiço', 'totalDeEncargos', 'mensalidade']])

      tempoDeServiço  totalDeEncargos  mensalidade
1059            <NA>          6350.50    86.599998
1097            <NA>              NaN   106.099998
1791            <NA>          1052.40    89.750000
1984            <NA>          8289.20   114.050003
2361            <NA>          2186.40    99.250000
2372            <NA>            19.55    19.549999
2641            <NA>          3615.60    99.150002
2896            <NA>          4131.20    61.450001
2936            <NA>           288.05    20.000000
2959            <NA>          7040.85   104.099998
3153            <NA>          1614.90    24.950001
3300            <NA>           171.00    25.100000
3388            <NA>          3321.35    49.349998
3476            <NA>            91.40    20.150000
3515            <NA>           455.30    91.099998
3837            <NA>          1441.65    19.600000
4875            <NA>          2602.90    92.349998
5324            <NA>          1614.05    69.449997
5328            <NA>          1482.30    20.700001

In [69]:
df.loc[7, "feedbackDoCliente"]
df.loc[7, "totalDeEncargos"] = 1129.5
df.loc[49, "totalDeEncargos"] = 74.9
df.loc[64, "totalDeEncargos"] =  335.8

In [71]:
df.loc[79, "feedbackDoCliente"]

'I have been a customer with this company for over three years now, and I have been mostly satisfied with the fiber optic internet service they provide. However, I recently decided to cancel my subscription due to the high monthly charges of $109.55. I found a better deal with another provider and felt it was time to make a change. I have always paid my bills on time with mailed checks, but the cost was just becoming too much for me to justify. Overall, I had a good experience with the internet service itself, but the pricing ultimately led me to churn.'