## Leitura do dataset CSV

## Importando bibliotecas
- Utilização de bibliotecas em todas as etapas (Bronze, Silver e Gold)

In [2]:
%pip install seaborn
%pip install pandas
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Requirement already satisfied: seaborn in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from seaborn) (2.5.2)
Requirement already satisfied: pandas>=1.2 in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from seaborn) (3.0.5)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from seaborn) (3.11.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.1)
Requirement already satisfied: packaging>=20.0 in C:\Users\52068085801\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.3)
Requirement already satisfied: pillow>=9 in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\52068085801\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas>=1.2->seaborn) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\52068085801\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.2.1 -> 26.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

[notice] A new release of pip is available: 26.2.1 -> 26.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pandas in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\52068085801\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\52068085801\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
df = pd.read_csv("history.csv")

# Conhecendo o Dataset: (Bronze)
- Primeiros e últimos registros do banco

In [4]:
df.head(10)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,CustomerFeedback,MonthlyIncome
0,4578-PHJYZ,Male,0,Yes,Yes,52,Yes,No,DSL,No,...,Yes,No,One year,Yes,Electronic check,68.75,3482.85,No,I have been a customer with this internet prov...,6532
1,6289-CPNLD,Male,0,Yes,Yes,33,Yes,No,DSL,No,...,Yes,Yes,One year,Yes,Mailed check,73.90,2405.05,Yes,I've been a customer with this company for ove...,7634
2,2682-KEVRP,Female,1,No,No,22,Yes,No,No,No internet service,...,No internet service,No internet service,One year,Yes,Mailed check,20.05,417.00,No,I have been a customer with this company for 2...,3628
3,5697-GOMBF,Female,1,Yes,Yes,28,No,No phone service,DSL,No,...,Yes,No,Month-to-month,Yes,Electronic check,35.90,973.65,No,I have been a customer with this internet prov...,7851
4,9717-QEBGU,Male,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Electronic check,70.30,144.00,No,I have been using the fiber optic internet ser...,1691
5,6797-LNAQX,Male,0,Yes,Yes,70,Yes,Yes,Fiber optic,No,...,Yes,Yes,Two year,No,Bank transfer (automatic),98.30,6859.50,Yes,I have been a customer with this company for 7...,5487
6,3050-GBUSH,Female,0,No,No,3,no,No phone service,DSL,No,...,Yes,No,Month-to-month,Yes,Credit card (automatic),34.80,113.95,No,I have been a customer with this DSL internet ...,6382
7,8020-BWHYL,Female,1,No,No,15,Yes,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Credit card (automatic),75.30,NaN,Yes,I recently canceled my service with this provi...,353
8,6752-APNJL,Male,0,Yes,Yes,42,Yes,No,DSL,Yes,...,No,No,Month-to-month,No,Mailed check,54.50,2301.15,No,I have been a customer with this company for 4...,2436
9,1760-CAZHT,Male,0,No,Yes,25,Yes,No,No,No internet service,...,No internet service,No internet service,Month-to-month,No,Mailed check,20.80,460.20,No,I have been a customer with this company for 2...,7049

In [5]:
df.tail(10)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,CustomerFeedback,MonthlyIncome
5624,8869-LIHMK,Female,0,No,No,64,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Two year,Yes,Bank transfer (automatic),115.10,7334.05,No,I have been a loyal customer of this company f...,5342
5625,0932-YIXYU,Female,0,No,No,47,yes,No,No,No internet service,...,No internet service,No internet service,Two year,No,Credit card (automatic),20.25,1029.80,No,I have been a customer with this company for a...,9229
5626,3569-EDBPQ,Female,0,No,No,24,Yes,Yes,Fiber optic,Yes,...,No,No,Month-to-month,Yes,Electronic check,84.35,1938.05,No,I have been a customer with this fiber optic i...,7165
5627,8645-KOMJQ,Male,0,Yes,Yes,69,Yes,Yes,DSL,No,...,Yes,Yes,Two year,Yes,Bank transfer (automatic),81.95,5601.40,No,I have been a loyal customer with this company...,411
5628,0786-IVLAW,Female,1,No,No,66,Yes,Yes,Fiber optic,No,...,Yes,Yes,One year,No,Bank transfer (automatic),108.10,7238.60,No,I have been a customer with this company for 6...,5113
5629,8909-BOLNL,Male,0,No,No,3,Yes,No,No,No internet service,...,No internet service,No internet service,One year,No,Mailed check,21.20,52.05,No,I have been a customer with this company for 3...,8354
5630,2832-KJCRD,Female,0,No,No,38,Yes,Yes,Fiber optic,No,...,Yes,Yes,Month-to-month,Yes,Electronic check,103.65,3988.50,No,I have been a customer with this company for 3...,9308
5631,7975-JMZNT,Male,0,Yes,No,66,Yes,Yes,DSL,Yes,...,Yes,Yes,Two year,No,Bank transfer (automatic),91.70,6075.90,No,I have been a customer with this DSL internet ...,2113
5632,4250-ZBWLV,Male,0,No,No,68,Yes,Yes,Fiber optic,No,...,Yes,Yes,One year,No,Electronic check,108.45,7176.55,Yes,I have been a customer with this company for o...,3904
5633,3915-ODIYG,Male,1,No,No,60,Yes,Yes,DSL,Yes,...,No,Yes,One year,Yes,Electronic check,71.75,4374.55,No,I have been a loyal customer of this internet ...,3016

### Dicionário de Dados do Dataset: (Bronze)

| Coluna           | Tradução                 | Definição resumida                                        |
| ---------------- | ------------------------ | --------------------------------------------------------- |
| customerID       | ID do cliente            | Código único de identificação do cliente.                 |
| gender           | Gênero                   | Gênero do cliente.                                        |
| SeniorCitizen    | Cidadão idoso            | Indica se o cliente é idoso (1 = sim, 0 = não).           |
| Partner          | Parceiro(a)              | Indica se o cliente possui companheiro(a).                |
| Dependents       | Dependentes              | Indica se o cliente possui dependentes.                   |
| tenure           | Tempo de permanência     | Tempo de relacionamento com a empresa, em meses.          |
| PhoneService     | Serviço telefônico       | Indica se o cliente possui telefone contratado.           |
| MultipleLines    | Múltiplas linhas         | Indica se possui mais de uma linha telefônica.            |
| InternetService  | Serviço de internet      | Tipo de serviço de internet contratado.                   |
| OnlineSecurity   | Segurança online         | Indica se possui serviço de segurança digital.            |
| OnlineBackup     | Backup online            | Indica se possui cópia de segurança de arquivos na nuvem. |
| DeviceProtection | Proteção de dispositivos | Indica se possui proteção para seus dispositivos.         |
| TechSupport      | Suporte técnico          | Indica se possui assistência técnica contratada.          |
| StreamingTV      | Transmissão de TV        | Indica se possui serviço de streaming de televisão.       |
| StreamingMovies  | Streaming de filmes      | Indica se possui serviço de streaming de filmes.          |
| Contract         | Contrato                 | Tipo e duração do contrato do cliente.                    |
| PaperlessBilling | Faturamento sem papel    | Indica se recebe a fatura digitalmente.                   |
| PaymentMethod    | Método de pagamento      | Forma utilizada para pagar pelos serviços.                |
| MonthlyCharges   | Cobranças mensais        | Valor cobrado mensalmente pelos serviços.                 |
| TotalCharges     | Cobranças totais         | Valor total acumulado cobrado do cliente.                 |
| Churn            | Cancelamento             | Indica se o cliente cancelou o serviço.                   |
| CustomerFeedback | Feedback do cliente      | Comentário do cliente sobre sua experiência.              |
| MonthlyIncome    | Renda mensal             | Valor da renda mensal do cliente.                         |

### Conhecendo o tipo dos dados e variaveis

In [6]:
df.dtypes
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5634 entries, 0 to 5633
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        5634 non-null   str
 1   gender            5634 non-null   str
 2   SeniorCitizen     5634 non-null   int64
 3   Partner           5634 non-null   str
 4   Dependents        5634 non-null   str
 5   tenure            5634 non-null   str
 6   PhoneService      5634 non-null   str
 7   MultipleLines     5634 non-null   str
 8   InternetService   5634 non-null   str
 9   OnlineSecurity    5634 non-null   str
 10  OnlineBackup      5634 non-null   str
 11  DeviceProtection  5634 non-null   str
 12  TechSupport       5634 non-null   str
 13  StreamingTV       5634 non-null   str
 14  StreamingMovies   5634 non-null   str
 15  Contract          5634 non-null   str
 16  PaperlessBilling  5634 non-null   str
 17  PaymentMethod     5634 non-null   str
 18  MonthlyCharges    5634 non-null   float64
 19  TotalCharges      5356 non-null   float64
 20  Churn             5634 non-null   str
 21  CustomerFeedback  5634 non-null   str
 22  MonthlyIncome     5634 non-null   int64
dtypes: float64(2), int64(2), str(19)
memory usage: 4.0 MB

### dicionario de dados

In [7]:
dicionario_dados = {
    "Variável Original": [
        "customerID", "gender", "SeniorCitizen", "Partner", "Dependents", "tenure",
        "PhoneService", "MultipleLines", "InternetService", "OnlineSecurity", "OnlineBackup",
        "DeviceProtection", "TechSupport", "StreamingTV", "StreamingMovies", "Contract",
        "PaperlessBilling", "PaymentMethod", "MonthlyCharges", "TotalCharges", "Churn",
        "CustomerFeedback", "MonthlyIncome"
    ],
    "Variável Traduzida": [
        "clienteID", "genero", "idoso", "conjuge", "dependentes", "tempoDeServiço",
        "serviçoTelefonico", "multiplasLinhasTelefonicas", "serviçoDeInternet",
        "segurançaOnline", "backupOnline", "proteçaoDeDispositivo", "suporteTecnico",
        "streamingTV", "streamingDeFilmes", "contrato", "faturaDigital",
        "metodoDePagamento", "mensalidade", "totalDeEncargos", "cancelamento",
        "feedbackDoCliente", "rendaMensal"
    ]
}

traducao = dict(zip(
    dicionario_dados["Variável Original"],
    dicionario_dados["Variável Traduzida"]
))

df = df.rename(columns=traducao)

# Transforma o dicionário em um DataFrame do Pandas
df_dicionario = pd.DataFrame(dicionario_dados)

print(df_dicionario.to_string(index=False))

Variável Original         Variável Traduzida
       customerID                  clienteID
           gender                     genero
    SeniorCitizen                      idoso
          Partner                    conjuge
       Dependents                dependentes
           tenure             tempoDeServiço
     PhoneService          serviçoTelefonico
    MultipleLines multiplasLinhasTelefonicas
  InternetService          serviçoDeInternet
   OnlineSecurity            segurançaOnline
     OnlineBackup               backupOnline
 DeviceProtection      proteçaoDeDispositivo
      TechSupport             suporteTecnico
      StreamingTV                streamingTV
  StreamingMovies          streamingDeFilmes
         Contract                   contrato
 PaperlessBilling              faturaDigital
    PaymentMethod          metodoDePagamento
   MonthlyCharges                mensalidade
     TotalCharges            totalDeEncargos
            Churn               cancelamento
 CustomerFeedback          feedbackDoCliente
    MonthlyIncome                rendaMensal

In [8]:
df["clienteID"] = df["clienteID"].astype("string")

df["genero"] = df["genero"].astype("category")

df["idoso"] = df["idoso"].astype("bool")

df["conjuge"] = df["conjuge"].astype("bool")

df["dependentes"] = df["dependentes"].astype("bool")

df["tempoDeServiço"] = pd.to_numeric(
    df["tempoDeServiço"].replace("unknown", pd.NA),
    errors="coerce"
).astype("Int8")

df["serviçoTelefonico"] = df["serviçoTelefonico"].astype("category")

df["multiplasLinhasTelefonicas"] = df["serviçoTelefonico"].astype("category")

df["serviçoDeInternet"] = df["serviçoDeInternet"].astype("category")

df["segurançaOnline"] = df["segurançaOnline"].astype("category")

df["backupOnline"] = df["backupOnline"].astype("category")

df["proteçaoDeDispositivo"] = df["proteçaoDeDispositivo"].astype("category")

df["suporteTecnico"] = df["suporteTecnico"].astype("category")

df["streamingTV"] = df["streamingTV"].astype("category")

df["streamingDeFilmes"] = df["streamingDeFilmes"].astype("category")

df["contrato"] = df["contrato"].astype("category")

df["faturaDigital"] = df["faturaDigital"].astype("bool")

df["metodoDePagamento"] = df["metodoDePagamento"].astype("category")

df["mensalidade"] = df["mensalidade"].astype("float32")

df["cancelamento"] = df["cancelamento"].astype("bool")

df["feedbackDoCliente"] = df["feedbackDoCliente"].astype("string")

df["rendaMensal"] = df["rendaMensal"].astype("int16")

In [9]:
print("Valor mínimo:", df["rendaMensal"].min())
print("Valor máximo:", df["rendaMensal"].max())

Valor mínimo: 100
Valor máximo: 9993

In [10]:
df.info(verbose=True)

<class 'pandas.DataFrame'>
RangeIndex: 5634 entries, 0 to 5633
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   clienteID                   5634 non-null   string
 1   genero                      5634 non-null   category
 2   idoso                       5634 non-null   bool
 3   conjuge                     5634 non-null   bool
 4   dependentes                 5634 non-null   bool
 5   tempoDeServiço              5615 non-null   Int8
 6   serviçoTelefonico           5634 non-null   category
 7   multiplasLinhasTelefonicas  5634 non-null   category
 8   serviçoDeInternet           5634 non-null   category
 9   segurançaOnline             5634 non-null   category
 10  backupOnline                5634 non-null   category
 11  proteçaoDeDispositivo       5634 non-null   category
 12  suporteTecnico              5634 non-null   category
 13  streamingTV                 5634 non-null   category
 14  streamingDeFilmes           5634 non-null   category
 15  contrato                    5634 non-null   category
 16  faturaDigital               5634 non-null   bool
 17  metodoDePagamento           5634 non-null   category
 18  mensalidade                 5634 non-null   float32
 19  totalDeEncargos             5356 non-null   float64
 20  cancelamento                5634 non-null   bool
 21  feedbackDoCliente           5634 non-null   string
 22  rendaMensal                 5634 non-null   int16
dtypes: Int8(1), bool(5), category(12), float32(1), float64(1), int16(1), string(2)
memory usage: 2.8 MB

In [11]:
df["rendaMensal"].unique()

array([6532, 7634, 3628, ..., 9308, 3904, 3016],
      shape=(4307,), dtype=int16)

In [12]:
for i,linha in df.iterrows():
    if linha.iloc[19:20].isnull().any():
        print(linha)

clienteID                                                            8020-BWHYL
genero                                                                   Female
idoso                                                                      True
conjuge                                                                    True
dependentes                                                                True
tempoDeServiço                                                               15
serviçoTelefonico                                                           Yes
multiplasLinhasTelefonicas                                                  Yes
serviçoDeInternet                                                   Fiber optic
segurançaOnline                                                              No
backupOnline                                                                Yes
proteçaoDeDispositivo                                                        No
suporteTecnico                                                               No
streamingTV                                                                  No
streamingDeFilmes                                                            No
contrato                                                         Month-to-month
faturaDigital                                                              True
metodoDePagamento                                       Credit card (automatic)
mensalidade                                                           75.300003
totalDeEncargos                                                             NaN
cancelamento                                                               True
feedbackDoCliente             I recently canceled my service with this provi...
rendaMensal                                                                 353
Name: 7, dtype: object
clienteID                                                            6996-KNSML
genero                                                                   Female
idoso                                                                     False
conjuge                                                                    True
dependentes                                                                True
tempoDeServiço                                                                1
serviçoTelefonico                                                           Yes
multiplasLinhasTelefonicas                                                  Yes
serviçoDeInternet                                                   Fiber optic
segurançaOnline                                                              No
backupOnline                                                                 No
proteçaoDeDispositivo                                                       Yes
suporteTecnico                                                               No
streamingTV                                                                  No
streamingDeFilmes                                                            No
contrato                                                         Month-to-month
faturaDigital                                                              True
metodoDePagamento                                              Electronic check
mensalidade                                                           74.900002
totalDeEncargos                                                             NaN
cancelamento                                                               True
feedbackDoCliente             I recently switched to this internet provider ...
rendaMensal                                                                5422
Name: 49, dtype: object
clienteID                                                            4951-UKAAQ
genero                                                                   Female
idoso                                                                     False
conjuge                                                                    True
dependentes                                                                True
tempoDeServiço                                                                4
serviçoTelefonico                                                           Yes
multiplasLinhasTelefonicas                                                  Yes
serviçoDeInternet                                                   Fiber optic
segurançaOnline                                                              No
backupOnline                                                                Yes
proteçaoDeDispositivo                                                        No
suporteTecnico                                                               No
streamingTV                                                                  No
streamingDeFilmes                                                           Yes
contrato                                                         Month-to-month
faturaDigital                                                              True
metodoDePagamento                                              Electronic check
mensalidade                                                           88.949997
totalDeEncargos                                                             NaN
cancelamento                                                               True
feedbackDoCliente             I recently decided to cancel my fiber optic in...
rendaMensal                                                                1323
Name: 64, dtype: object
clienteID                                                            9360-AHGNL
genero                                                                   Female
idoso                                                                      True
conjuge                                                                    True
dependentes                                                                True
tempoDeServiço                                                               43
serviçoTelefonico                                                           Yes
multiplasLinhasTelefonicas                                                  Yes
serviçoDeInternet                                                   Fiber optic
segurançaOnline                                                             Yes
backupOnline                                                                 No
proteçaoDeDispositivo                                                       Yes
suporteTecnico                                                              Yes
streamingTV                                                                 Yes
streamingDeFilmes                                                           Yes
contrato                                                               One year
faturaDigital                                                              True
metodoDePagamento                                                  Mailed check
mensalidade                                                          109.550003
totalDeEncargos                                                             NaN
cancelamento                                                               True
feedbackDoCliente             I have been a customer with this company for o...
rendaMensal                                                                6588
Name: 79, dtype: object
clienteID                                                            7253-UVNDW
genero                                                                   Female
idoso                                                                     False
conjuge                                                                    True
dependentes                                                                True
tempoDeServiço                                                               46
serviçoTelefonico                                                           Yes
multiplasLinhasTelefonicas                                                  Yes
serviçoDeInternet                                                           DSL
segurançaOnline                                                              No
backupOnline                                                                 No
proteçaoDeDispositivo                                                       Yes
suporteTecnico                                                              Yes
streamingTV                                                                  No
streamingDeFilmes                                                            No
contrato                                                               Two year
faturaDigital                                                              True
metodoDePagamento                                       Credit card (automatic)
mensalidade                                                           54.349998
totalDeEncargos                                                             NaN
cancelamento                                                               True
feedbackDoCliente             I have been a customer with this company for 4...
rendaMensal                                                                5277
Name: 122, dtype: object
clienteID                                                            4980-URKXC
genero                                                                     Male
idoso                                                                     False
conjuge                                                                    True
dependentes                                                                True
tempoDeServiço                                                               36
serviçoTelefonico                                                           Yes
multiplasLinhasTelefonicas                                                  Yes
serviçoDeInternet                                                            No
segurançaOnline                                             No internet service
backupOnline                                                No internet service
proteçaoDeDispositivo                                       No internet service
suporteTecnico                                              No internet service
streamingTV                                                 No internet service
streamingDeFilmes                                           No internet service
contrato                                                               One year
faturaDigital                                                              True
metodoDePagamento                                     Bank transfer (automatic)
mensalidade                                                               20.85
totalDeEncargos                                                             NaN
cancelamento                                                               True
feedbackDoCliente             I have been a customer with this company for 3...
rendaMensal                                                                1408
Name: 138, dtype: object
clienteID                                                            4946-EDSEW
genero                                                                   Female
idoso                                                                     False
conjuge                                                                    True
dependentes                                                                True
tempoDeServiço                                                               11
serviçoTelefonico                                                           Yes
multiplasLinhasTelefonicas                                                  Yes
serviçoDeInternet                                                            No
segurançaOnline                                             No internet service
backupOnline                                                No internet service
proteçaoDeDispositivo                                       No internet service
suporteTecnico                                              No internet service
streamingTV                                                 No internet service
streamingDeFilmes                                           No internet service
contrato                                                         Month-to-month
faturaDigital                                                              True
metodoDePagamento                                                  Mailed check
mensalidade                                                               19.25
totalDeEncargos                                                             NaN
cancelamento                                                               True
feedbackDoCliente             I decided to cancel my service after 11 months...
rendaMensal                                                                8314
Name: 139, dtype: object
clienteID                                                            1660-HSOOQ
genero                                                                     Male
idoso                                                                     False
conjuge                                                                    True
dependentes                                                                True
tempoDeServiço                                                                1
serviçoTelefonico                                                           Yes
multiplasLinhasTelefonicas                                                  Yes
serviçoDeInternet                                                           DSL
segurançaOnline                                                              No
backupOnline                                                                 No
proteçaoDeDispositivo                                                       Yes
suporteTecnico                                                               No
streamingTV                                                                  No
streamingDeFilmes                                                            No
contrato                                                         Month-to-month
faturaDigital                                                              True
metodoDePagamento                                                  Mailed check
mensalidade                                                           49.650002
totalDeEncargos                                                             NaN
cancelamento                                                               True
feedbackDoCliente             I am disappointed with my experience with this...
rendaMensal                                                                1768
Name: 143, dtype: object
clienteID                                                            3572-UUHRS
genero                                                                     Male
idoso                                                                     False
conjuge                                                                    True
dependentes                                                                True
tempoDeServiço                                                               45
serviçoTelefonico                                                           Yes
multiplasLinhasTelefonicas                                                  Yes
serviçoDeInternet                                                            No
segurançaOnline                                             No internet service
backupOnline                                                No internet service
proteçaoDeDispositivo                                       No internet service
suporteTecnico                                              No internet service
streamingTV                                                 No internet service
streamingDeFilmes                                           No internet service
contrato                                                               One year
faturaDigital                                                              True
metodoDePagamento                                     Bank transfer (automatic)
mensalidade                                                               18.85
totalDeEncargos                                                             NaN
cancelamento                                                               True
feedbackDoCliente             I have been a customer with this company for o...
rendaMensal                                                                7917
Name: 162, dtype: object
clienteID                                                            8167-GJLRN
genero                                                                     Male
idoso                                                                     False
conjuge                                                                    True
dependentes                                                                True
tempoDeServiço                                                                3
serviçoTelefonico                                                            No
multiplasLinhasTelefonicas                                                   No
serviçoDeInternet                                                           DSL
segurançaOnline                                                              No
backupOnline                                                                 No
proteçaoDeDispositivo                                                        No
suporteTecnico                                                              Yes
streamingTV                                                                  No
streamingDeFilmes                                                            No
contrato                                                         Month-to-month
faturaDigital                                                              True
metodoDePagamento                                              Electronic check
mensalidade                                                                30.4
totalDeEncargos                                                             NaN
cancelamento                                                               True
feedbackDoCliente             I have been a customer with this DSL internet ...
rendaMensal                                                                9137
Name: 176, dtype: object
clienteID                                                            9522-BNTHX
genero                                                                   Female
idoso                                                                      True
conjuge                                                                    True
dependentes                                                                True
tempoDeServiço                                                               34
serviçoTelefonico                                                            No
multiplasLinhasTelefonicas                                                   No
serviçoDeInternet                                                           DSL
segurançaOnline                                                              No
backupOnline                                                                Yes
proteçaoDeDispositivo                                                       Yes
suporteTecnico                                                               No
streamingTV                                                                 Yes
streamingDeFilmes                                                           Yes
contrato                                                         Month-to-month

In [13]:
df.loc[5629]

clienteID                                                            8909-BOLNL
genero                                                                     Male
idoso                                                                     False
conjuge                                                                    True
dependentes                                                                True
tempoDeServiço                                                                3
serviçoTelefonico                                                           Yes
multiplasLinhasTelefonicas                                                  Yes
serviçoDeInternet                                                            No
segurançaOnline                                             No internet service
backupOnline                                                No internet service
proteçaoDeDispositivo                                       No internet service
suporteTecnico                                              No internet service
streamingTV                                                 No internet service
streamingDeFilmes                                           No internet service
contrato                                                               One year
faturaDigital                                                              True
metodoDePagamento                                                  Mailed check
mensalidade                                                           21.200001
totalDeEncargos                                                           52.05
cancelamento                                                               True
feedbackDoCliente             I have been a customer with this company for 3...
rendaMensal                                                                8354
Name: 5629, dtype: object

In [14]:
df[df["clienteID"] == "8909-BOLNL"][
    ["clienteID", "tempoDeServiço", "mensalidade", "totalDeEncargos"]
]
print(df[df["clienteID"] == "8909-BOLNL"][
    ["clienteID", "tempoDeServiço", "mensalidade", "totalDeEncargos"]
])

       clienteID  tempoDeServiço  mensalidade  totalDeEncargos
5629  8909-BOLNL               3    21.200001            52.05

In [15]:
## todos com tempo de serviço nulo
df[df["tempoDeServiço"].isnull()][["clienteID", "tempoDeServiço", "mensalidade", "totalDeEncargos"]]

       clienteID  tempoDeServiço  mensalidade  totalDeEncargos
1059  7301-ABVAD            <NA>    86.599998          6350.50
1097  9651-GTSAQ            <NA>   106.099998              NaN
1791  0135-NMXAP            <NA>    89.750000          1052.40
1984  3892-NXAZG            <NA>   114.050003          8289.20
2361  3934-HXCFZ            <NA>    99.250000          2186.40
2372  1622-HSHSF            <NA>    19.549999            19.55
2641  6907-NZZIJ            <NA>    99.150002          3615.60
2896  6023-GSSXW            <NA>    61.450001          4131.20
2936  5688-KZTSN            <NA>    20.000000           288.05
2959  7694-VLBWQ            <NA>   104.099998          7040.85
3153  1619-YWUBB            <NA>    24.950001          1614.90
3300  9575-IWCAZ            <NA>    25.100000           171.00
3388  4702-HDRKD            <NA>    49.349998          3321.35
3476  6469-QJKZW            <NA>    20.150000            91.40
3515  2672-HUYVI            <NA>    91.099998           455.30
3837  3274-NSDWE            <NA>    19.600000          1441.65
4875  3348-CFRNX            <NA>    92.349998          2602.90
5324  6614-VBEGU            <NA>    69.449997          1614.05
5328  1293-BSEUN            <NA>    20.700001          1482.30

### Filtrando feedback para descobrir o total de encargos e mensalidade de um cliente específico
- Feeback do cliente é de mais de 6 meses, mas o registro

In [37]:
## filtrando feedback onde o tempo de serviço é nulo, para descobrir o total de encargos e mensalidade de um cliente específico
df[df["feedbackDoCliente"].notnull() & df["tempoDeServiço"].isnull()][["clienteID", "feedbackDoCliente", "totalDeEncargos", "mensalidade","tempoDeServiço"]]

,clienteID,feedbackDoCliente,totalDeEncargos,mensalidade,tempoDeServiço
3515,2672-HUYVI,I recently canceled my service after being a c...,455.3,91.099998,<NA>

## Registros onde o tempo de serviço eram nulos, mas haviam feedbacks com tempo de serviço válido

In [ ]:
#df.loc[1097,'tempoDeServiço'] = 48
#df.loc[1791,'tempoDeServiço'] = 12
#df.loc[1984,'tempoDeServiço'] = 72
#df.loc[2361,'tempoDeServiço'] = 22
#df.loc[2372,'tempoDeServiço'] = 1
#df.loc[3837,'tempoDeServiço'] = 73
#df.loc[5328,'tempoDeServiço'] = 72
#df.loc[4875,'tempoDeServiço'] = 28
#df.loc[1059,'tempoDeServiço'] = 72
#df.loc[5324,'tempoDeServiço'] = 24
#df.loc[3476,'tempoDeServiço'] = 4
#df.loc[2896,'tempoDeServiço'] = 67
#df.loc[3153,'tempoDeServiço'] = 64
#df.loc[3388,'tempoDeServiço'] = 67
#df.loc[2641,'tempoDeServiço'] = 36
#df.loc[2936,'tempoDeServiço'] = 15
#df.loc[2959,'tempoDeServiço'] = 67
#df.loc[3300,'tempoDeServiço'] = 6
#df.loc[3515,'tempoDeServiço'] = 5

,clienteID,genero,idoso,conjuge,dependentes,tempoDeServiço,serviçoTelefonico,multiplasLinhasTelefonicas,serviçoDeInternet,segurançaOnline,...,streamingTV,streamingDeFilmes,contrato,faturaDigital,metodoDePagamento,mensalidade,totalDeEncargos,cancelamento,feedbackDoCliente,rendaMensal
1059,7301-ABVAD,Female,False,True,True,6,Yes,Yes,DSL,No,...,Yes,Yes,Two year,True,Bank transfer (automatic),86.599998,6350.5,True,I have been a customer with this company for 6...,3093

<class 'pandas.DataFrame'>
RangeIndex: 5634 entries, 0 to 5633
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   clienteID                   5634 non-null   string
 1   genero                      5634 non-null   category
 2   idoso                       5634 non-null   bool
 3   conjuge                     5634 non-null   bool
 4   dependentes                 5634 non-null   bool
 5   tempoDeServiço              5634 non-null   Int8
 6   serviçoTelefonico           5634 non-null   category
 7   multiplasLinhasTelefonicas  5634 non-null   category
 8   serviçoDeInternet           5634 non-null   category
 9   segurançaOnline             5634 non-null   category
 10  backupOnline                5634 non-null   category
 11  proteçaoDeDispositivo       5634 non-null   category
 12  suporteTecnico              5634 non-null   category
 13  streamingTV                 5634 non-null   category
 14  streamingDeFilmes           5634 non-null   category
 15  contrato                    5634 non-null   category
 16  faturaDigital               5634 non-null   bool
 17  metodoDePagamento           5634 non-null   category
 18  mensalidade                 5634 non-null   float32
 19  totalDeEncargos             5356 non-null   float64
 20  cancelamento                5634 non-null   bool
 21  feedbackDoCliente           5634 non-null   string
 22  rendaMensal                 5634 non-null   int16
dtypes: Int8(1), bool(5), category(12), float32(1), float64(1), int16(1), string(2)
memory usage: 2.8 MB